baseurl = "http://blog.konglingjian.com/"
languageCode = "zh-CN"
title = "Alex kong"
theme = "hugo-pacman-theme"
Categories = ["技术", "生活", "工具"]
Description = ""
Tags = []

[Author]
    Name = "Alex kong"
    homepage = "http://blog.konglingjian.com"
[Params]
    description = "这里是Alex kong的个人博客"
    themeColor = "theme-base-08" # for hyde theme
    Subtitle = "我是一个工作生活在北京的程序猿"
    Weibo = "klj123wan"
    WeiboID = 18618303816
    Twitter = "klj123wan"
    GitHub = "klj123wan"
    Facebook = "alex.konglingjian"
    LinkIn = "in/18618303816"
    Imglogo = "img/logo.jpg"
    AuthorImg = "img/author.jpg"
    DateFormat = "2006年01月02日"
    MonthFormat = "2006年01月"
    FancyBox = true
[Params.Disqus]
    ShortName = "konglingjian"

[Params.GoogleAnalytics]
    ID = "UA-79782250-1"

[Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2
